language: go

go:
  - 1.15.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress

after_success:
  - bash <(curl -s https://codecov.io/bash)