language: go

go:
  - 1.15.x
  - tip

before_install:
  - go get -t -v ./...
  - sudo apt-get -y install golang-ginkgo-dev
  - sudo apt-get install -y xsel

script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --progress

after_success:
  - bash <(curl -s https://codecov.io/bash)